name: Node CI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm bootstrap & build
      run: |
        npm run bootstrap
        npm run build --if-present
        #npm run docs (runs webserver)
      env:
        CI: true
    - uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: enwaytech/webviz/webwiz:latest
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        username: stefan-enway
        password: ${{ secrets.GITHUB_TOKEN }}
